<?php
			$optionsArray = array( 'totals' => array( 'id_admin' => array( 'totalsType' => '' ),
'paciente_id' => array( 'totalsType' => '' ),
'fecha_hora' => array( 'totalsType' => '' ),
'cantidad_ordenada' => array( 'totalsType' => '' ),
'cantidad_administrada' => array( 'totalsType' => '' ),
'via' => array( 'totalsType' => '' ),
'tipo' => array( 'totalsType' => '' ),
'enfermero' => array( 'totalsType' => '' ),
'hora_inicial' => array( 'totalsType' => '' ),
'hora_final' => array( 'totalsType' => '' ),
'liquido' => array( 'totalsType' => '' ),
'cantidad' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_admin',
'paciente_id',
'fecha_hora',
'cantidad_ordenada',
'cantidad_administrada',
'via',
'tipo',
'enfermero',
'hora_inicial',
'hora_final',
'liquido',
'cantidad' ),
'exportFields' => array( 'id_admin',
'paciente_id',
'fecha_hora',
'cantidad_ordenada',
'cantidad_administrada',
'via',
'tipo',
'enfermero',
'hora_inicial',
'hora_final',
'liquido',
'cantidad' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_admin' => array( 'export_field' ),
'paciente_id' => array( 'export_field1' ),
'fecha_hora' => array( 'export_field2' ),
'cantidad_ordenada' => array( 'export_field3' ),
'cantidad_administrada' => array( 'export_field4' ),
'via' => array( 'export_field5' ),
'tipo' => array( 'export_field6' ),
'enfermero' => array( 'export_field7' ),
'hora_inicial' => array( 'export_field8' ),
'hora_final' => array( 'export_field9' ),
'liquido' => array( 'export_field10' ),
'cantidad' => array( 'export_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_admin',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'paciente_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'fecha_hora',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'cantidad_ordenada',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cantidad_administrada',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'via',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'tipo',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'enfermero',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'hora_inicial',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'hora_final',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'liquido',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cantidad',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>