<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_admin',
'paciente_id',
'fecha_hora',
'cantidad_ordenada',
'cantidad_administrada',
'via',
'tipo',
'enfermero',
'hora_inicial',
'hora_final',
'liquido',
'cantidad' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_admin' => array( 'import_field' ),
'paciente_id' => array( 'import_field1' ),
'fecha_hora' => array( 'import_field2' ),
'cantidad_ordenada' => array( 'import_field3' ),
'cantidad_administrada' => array( 'import_field4' ),
'via' => array( 'import_field5' ),
'tipo' => array( 'import_field6' ),
'enfermero' => array( 'import_field7' ),
'hora_inicial' => array( 'import_field8' ),
'hora_final' => array( 'import_field9' ),
'liquido' => array( 'import_field10' ),
'cantidad' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_admin',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'paciente_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'fecha_hora',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cantidad_ordenada',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cantidad_administrada',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'via',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'tipo',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'enfermero',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'hora_inicial',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'hora_final',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'liquido',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cantidad',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>