<?php
			$optionsArray = array( 'totals' => array( 'id_paciente' => array( 'totalsType' => '' ),
'tipo_documento' => array( 'totalsType' => '' ),
'identificacion' => array( 'totalsType' => '' ),
'primer_nombre' => array( 'totalsType' => '' ),
'segundo_nombre' => array( 'totalsType' => '' ),
'primer_apellido' => array( 'totalsType' => '' ),
'segundo_apellido' => array( 'totalsType' => '' ),
'nombre_completo' => array( 'totalsType' => '' ),
'edad' => array( 'totalsType' => '' ),
'sexo' => array( 'totalsType' => '' ),
'estado_civil' => array( 'totalsType' => '' ),
'telefono' => array( 'totalsType' => '' ),
'direccion' => array( 'totalsType' => '' ),
'ciudad_mpio' => array( 'totalsType' => '' ),
'entidad_eapb' => array( 'totalsType' => '' ),
'riesgo' => array( 'totalsType' => '' ),
'cama' => array( 'totalsType' => '' ),
'servicio' => array( 'totalsType' => '' ),
'motivo_consulta' => array( 'totalsType' => '' ),
'turno' => array( 'totalsType' => '' ),
'fecha_ingreso' => array( 'totalsType' => '' ),
'creado_en' => array( 'totalsType' => '' ),
'actualizado_en' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_paciente',
'tipo_documento',
'identificacion',
'primer_nombre',
'segundo_nombre',
'primer_apellido',
'segundo_apellido',
'nombre_completo',
'edad',
'sexo',
'estado_civil',
'telefono',
'direccion',
'ciudad_mpio',
'entidad_eapb',
'riesgo',
'cama',
'servicio',
'motivo_consulta',
'turno',
'fecha_ingreso',
'creado_en',
'actualizado_en' ),
'exportFields' => array( 'id_paciente',
'tipo_documento',
'identificacion',
'primer_nombre',
'segundo_nombre',
'primer_apellido',
'segundo_apellido',
'nombre_completo',
'edad',
'sexo',
'estado_civil',
'telefono',
'direccion',
'ciudad_mpio',
'entidad_eapb',
'riesgo',
'cama',
'servicio',
'motivo_consulta',
'turno',
'fecha_ingreso',
'creado_en',
'actualizado_en' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_paciente' => array( 'export_field' ),
'tipo_documento' => array( 'export_field1' ),
'identificacion' => array( 'export_field2' ),
'primer_nombre' => array( 'export_field3' ),
'segundo_nombre' => array( 'export_field4' ),
'primer_apellido' => array( 'export_field5' ),
'segundo_apellido' => array( 'export_field6' ),
'nombre_completo' => array( 'export_field7' ),
'edad' => array( 'export_field8' ),
'sexo' => array( 'export_field9' ),
'estado_civil' => array( 'export_field10' ),
'telefono' => array( 'export_field11' ),
'direccion' => array( 'export_field12' ),
'ciudad_mpio' => array( 'export_field13' ),
'entidad_eapb' => array( 'export_field14' ),
'riesgo' => array( 'export_field15' ),
'cama' => array( 'export_field16' ),
'servicio' => array( 'export_field17' ),
'motivo_consulta' => array( 'export_field18' ),
'turno' => array( 'export_field19' ),
'fecha_ingreso' => array( 'export_field20' ),
'creado_en' => array( 'export_field21' ),
'actualizado_en' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_paciente',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'tipo_documento',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'identificacion',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'primer_nombre',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'segundo_nombre',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'primer_apellido',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'segundo_apellido',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'nombre_completo',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'edad',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'sexo',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'estado_civil',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'telefono',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'direccion',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'ciudad_mpio',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'entidad_eapb',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'riesgo',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'cama',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'servicio',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'motivo_consulta',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'turno',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'fecha_ingreso',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'creado_en',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'actualizado_en',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>