<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_paciente',
'tipo_documento',
'identificacion',
'primer_nombre',
'segundo_nombre',
'primer_apellido',
'segundo_apellido',
'nombre_completo',
'edad',
'sexo',
'estado_civil',
'telefono',
'direccion',
'ciudad_mpio',
'entidad_eapb',
'riesgo',
'cama',
'servicio',
'motivo_consulta',
'turno',
'fecha_ingreso',
'creado_en',
'actualizado_en' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_paciente' => array( 'import_field' ),
'tipo_documento' => array( 'import_field1' ),
'identificacion' => array( 'import_field2' ),
'primer_nombre' => array( 'import_field3' ),
'segundo_nombre' => array( 'import_field4' ),
'primer_apellido' => array( 'import_field5' ),
'segundo_apellido' => array( 'import_field6' ),
'nombre_completo' => array( 'import_field7' ),
'edad' => array( 'import_field8' ),
'sexo' => array( 'import_field9' ),
'estado_civil' => array( 'import_field10' ),
'telefono' => array( 'import_field11' ),
'direccion' => array( 'import_field12' ),
'ciudad_mpio' => array( 'import_field13' ),
'entidad_eapb' => array( 'import_field14' ),
'riesgo' => array( 'import_field15' ),
'cama' => array( 'import_field16' ),
'servicio' => array( 'import_field17' ),
'motivo_consulta' => array( 'import_field18' ),
'turno' => array( 'import_field19' ),
'fecha_ingreso' => array( 'import_field20' ),
'creado_en' => array( 'import_field21' ),
'actualizado_en' => array( 'import_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_paciente',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'tipo_documento',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'identificacion',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'primer_nombre',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'segundo_nombre',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'primer_apellido',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'segundo_apellido',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'nombre_completo',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'edad',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'sexo',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'estado_civil',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'telefono',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'direccion',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'ciudad_mpio',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'entidad_eapb',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'riesgo',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'cama',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'servicio',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'motivo_consulta',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'turno',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'fecha_ingreso',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'creado_en',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'actualizado_en',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>